version: "3.9"

services:
  web:
    image: test1-frontend-compose-814e04-web:latest
    build: .
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3002}
    # volumes:
    #   - "./app:/usr/src/app"
    ports:
      - "3002:3002"