version: "3.9"

services:
  web:
    build: .
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - author=someone
      - var2=value2
    # volumes:
    #   - "./app:/usr/src/app"
    ports:
      - "3001:3000"